spring.application.name=SMART-SHOP
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update






spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=youssefhaddaq2004@gmail.com

spring.mail.password=ekoedzohuvjnrtwj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true